import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatCurrency, formatDate } from "@/lib/utils";

interface InvoicePdfData {
  invoiceNumber: string;
  issueDate: Date;
  dueDate: Date;
  business: {
    name: string;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    city?: string | null;
    mpesaTill?: string | null;
    mpesaPaybill?: string | null;
  };
  client?: {
    name: string;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  } | null;
  items: Array<{
    description: string;
    quantity: string;
    unitPrice: string;
    amount: string;
  }>;
  subtotal: string;
  taxRate: string;
  taxAmount: string;
  total: string;
  amountPaid: string;
  currency: string;
  notes?: string | null;
  terms?: string | null;
}

export function generateInvoicePdf(data: InvoicePdfData): Buffer {
  const doc = new jsPDF();
  const currency = data.currency || "KES";

  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 107, 63);
  doc.text(data.business.name, 20, 25);

  doc.setFontSize(10);
  doc.setTextColor(100);
  if (data.business.email) doc.text(data.business.email, 20, 32);
  if (data.business.phone) doc.text(data.business.phone, 20, 37);
  if (data.business.address)
    doc.text(`${data.business.address}, ${data.business.city || ""}`, 20, 42);

  doc.setFontSize(24);
  doc.setTextColor(30);
  doc.text("INVOICE", 150, 25);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`#${data.invoiceNumber}`, 150, 32);
  doc.text(`Issue: ${formatDate(data.issueDate)}`, 150, 37);
  doc.text(`Due: ${formatDate(data.dueDate)}`, 150, 42);

  // Bill To
  let y = 60;
  doc.setFontSize(11);
  doc.setTextColor(30);
  doc.text("Bill To:", 20, y);
  y += 6;
  doc.setFontSize(10);
  doc.setTextColor(80);
  if (data.client) {
    doc.text(data.client.name, 20, y);
    y += 5;
    if (data.client.email) {
      doc.text(data.client.email, 20, y);
      y += 5;
    }
    if (data.client.phone) {
      doc.text(data.client.phone, 20, y);
      y += 5;
    }
  } else {
    doc.text("No client selected", 20, y);
    y += 5;
  }

  // Items table
  autoTable(doc, {
    startY: y + 10,
    head: [["Description", "Qty", "Unit Price", "Amount"]],
    body: data.items.map((item) => [
      item.description,
      item.quantity,
      formatCurrency(item.unitPrice, currency),
      formatCurrency(item.amount, currency),
    ]),
    theme: "striped",
    headStyles: { fillColor: [0, 107, 63] },
  });

  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } })
    .lastAutoTable.finalY + 10;

  // Totals
  const totalsX = 130;
  doc.setFontSize(10);
  doc.text("Subtotal:", totalsX, finalY);
  doc.text(formatCurrency(data.subtotal, currency), 180, finalY, {
    align: "right",
  });

  doc.text(`VAT (${data.taxRate}%):`, totalsX, finalY + 6);
  doc.text(formatCurrency(data.taxAmount, currency), 180, finalY + 6, {
    align: "right",
  });

  doc.setFontSize(12);
  doc.setTextColor(0, 107, 63);
  doc.text("Total:", totalsX, finalY + 14);
  doc.text(formatCurrency(data.total, currency), 180, finalY + 14, {
    align: "right",
  });

  const paid = parseFloat(data.amountPaid);
  if (paid > 0) {
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text("Amount Paid:", totalsX, finalY + 22);
    doc.text(formatCurrency(data.amountPaid, currency), 180, finalY + 22, {
      align: "right",
    });
    doc.text("Balance Due:", totalsX, finalY + 28);
    doc.text(
      formatCurrency(parseFloat(data.total) - paid, currency),
      180,
      finalY + 28,
      { align: "right" }
    );
  }

  // Payment info
  let payY = finalY + 40;
  if (data.business.mpesaTill || data.business.mpesaPaybill) {
    doc.setFontSize(10);
    doc.setTextColor(30);
    doc.text("Payment via M-Pesa:", 20, payY);
    payY += 6;
    doc.setTextColor(80);
    if (data.business.mpesaTill)
      doc.text(`Till Number: ${data.business.mpesaTill}`, 20, payY);
  }

  // Notes
  if (data.notes) {
    payY += 15;
    doc.setTextColor(30);
    doc.text("Notes:", 20, payY);
    doc.setTextColor(80);
    doc.text(data.notes, 20, payY + 6, { maxWidth: 170 });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by KaziFlow — kaziflow.co.ke", 105, 285, {
    align: "center",
  });

  return Buffer.from(doc.output("arraybuffer"));
}
