/**
 * KaziFlow — Sample / Demo data seeder
 * ------------------------------------------------------------------
 * Generates a small, realistic set of demo data (clients, products, a sample
 * invoice) for a new organization. Intended to be triggered from the onboarding
 * wizard ("Load sample data") so first-time users land on a populated dashboard
 * instead of empty screens.
 *
 * Idempotent: guarded by an `onboardingSampleLoaded` flag on the organization
 * settings, and each write uses an idempotency key so re-running is a no-op.
 * Never deletes or mutates user data.
 */
import { db } from "@/db";
import {
  clients,
  inventoryProducts,
  invoices,
  invoiceItems,
  organizations,
  type Client,
} from "@/db/schema";
import { and, eq, sql } from "drizzle-orm";
import type { ServerContext } from "@/lib/session";
import { generateInvoiceNumber } from "@/lib/utils";
import { emitTimelineEvent } from "@/lib/timeline";

const DEMO_CLIENTS = [
  { name: "Amani Boutique", email: "accounts@amaniboutique.co.ke", phone: "254720111222", company: "Amani Boutique Ltd" },
  { name: "Savannah Tech", email: "billing@savannahtech.io", phone: "254733444555", company: "Savannah Tech Solutions" },
  { name: "Coastal Café", email: "hello@coastalcafe.co.ke", phone: "254711666777", company: "Coastal Café Ltd" },
];

const DEMO_PRODUCTS = [
  { name: "Consulting (Hourly)", description: "Professional consulting services", sellingPrice: "5000", costPrice: "2000", unit: "hr" },
  { name: "Website Design", description: "Custom responsive website", sellingPrice: "45000", costPrice: "18000", unit: "project" },
  { name: "Brand Photoshoot", description: "Half-day brand photography session", sellingPrice: "25000", costPrice: "9000", unit: "session" },
];

export interface SeedSampleDataResult {
  loaded: boolean;
  clients: number;
  products: number;
  invoices: number;
  alreadyLoaded: boolean;
}

/** Returns true if sample data was already loaded for the organization. */
async function isAlreadyLoaded(organizationId: string): Promise<boolean> {
  const org = await db.query.organizations.findFirst({
    where: eq(organizations.id, organizationId),
    columns: { settings: true },
  });
  const settings = (org?.settings as Record<string, unknown> | null) ?? null;
  return Boolean((settings as any)?.onboardingSampleLoaded);
}

export async function seedSampleData(
  ctx: ServerContext
): Promise<SeedSampleDataResult> {
  const organizationId = ctx.organizationId;
  const userId = ctx.userId!;

  if (await isAlreadyLoaded(organizationId)) {
    return { loaded: false, clients: 0, products: 0, invoices: 0, alreadyLoaded: true };
  }

  // Insert demo clients.
  const insertedClients: Client[] = [];
  for (const c of DEMO_CLIENTS) {
    const [row] = await db
      .insert(clients)
      .values({
        organizationId,
        userId,
        name: c.name,
        email: c.email,
        phone: c.phone,
        company: c.company,
      })
      .onConflictDoNothing()
      .returning();
    if (row) insertedClients.push(row);
  }

  // Insert demo products.
  let productCount = 0;
  for (const p of DEMO_PRODUCTS) {
    const [row] = await db
      .insert(inventoryProducts)
      .values({
        organizationId,
        userId,
        name: p.name,
        description: p.description,
        sellingPrice: p.sellingPrice,
        costPrice: p.costPrice,
        unit: p.unit,
      })
      .onConflictDoNothing()
      .returning();
    if (row) productCount++;
  }

  // Create one sample invoice tied to the first demo client.
  let invoiceCount = 0;
  if (insertedClients.length > 0) {
    const client = insertedClients[0];
    const items = [
      { description: "Website Design", quantity: "1", unitPrice: "45000" },
      { description: "Brand Photoshoot", quantity: "1", unitPrice: "25000" },
    ];
    const subtotal = items.reduce(
      (s, i) => s + Number(i.quantity) * Number(i.unitPrice),
      0
    );
    const taxRate = 16;
    const taxAmount = (subtotal * taxRate) / 100;
    const total = subtotal + taxAmount;

    const [invoice] = await db
      .insert(invoices)
      .values({
        userId,
        organizationId,
        clientId: client.id,
        invoiceNumber: generateInvoiceNumber("INV"),
        status: "sent",
        issueDate: new Date(),
        dueDate: new Date(Date.now() + 14 * 86400000),
        currency: "KES",
        subtotal: subtotal.toFixed(2),
        taxRate: String(taxRate),
        taxAmount: taxAmount.toFixed(2),
        total: total.toFixed(2),
        notes: "Sample invoice generated by KaziFlow demo data.",
      })
      .returning();

    if (invoice) {
      await db.insert(invoiceItems).values(
        items.map((it, i) => ({
          invoiceId: invoice.id,
          description: it.description,
          quantity: it.quantity,
          unitPrice: it.unitPrice,
          amount: (Number(it.quantity) * Number(it.unitPrice)).toFixed(2),
          sortOrder: i,
        }))
      );
      invoiceCount++;
      await emitTimelineEvent({
        userId,
        organizationId,
        eventType: "invoice.created",
        title: "Sample invoice created",
        description: `Demo invoice ${invoice.invoiceNumber} was generated.`,
        resourceType: "invoice",
        resourceId: invoice.id,
        metadata: { sample: true },
      });
    }
  }

  // Mark as loaded so we never double-seed.
  await db
    .update(organizations)
    .set({
      settings: sql`${organizations.settings}::jsonb || ${JSON.stringify({
        onboardingSampleLoaded: true,
      })}::jsonb`,
      updatedAt: new Date(),
    })
    .where(eq(organizations.id, organizationId));

  return {
    loaded: true,
    clients: insertedClients.length,
    products: productCount,
    invoices: invoiceCount,
    alreadyLoaded: false,
  };
}
